apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config
      version: "1.0"
  template:
    metadata:
      labels:
        app: config
        version: "1.0"
    spec:
      containers:
      - name: config
        image: vitorbertazoli/config:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
