version: '2'
services:
    config:
        image: config
        environment:
            - SPRING_PROFILES_ACTIVE=prod
#            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${eureka.registry.password}@eureka-registry:8761/eureka
#            - SPRING_CLOUD_CONFIG_URI=http://admin:$${eureka.registry.password}@eureka-registry:8761/config
        ports:
          - 8081:8081
